version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: cron
      cronjob: '0 9 * * *'
      timezone: America/Sao_Paulo
    cooldown:
      default-days: 0
    versioning-strategy: increase
    groups:
      npm-dependencies:
        patterns: ['*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: cron
      cronjob: '0 9 * * *'
      timezone: America/Sao_Paulo
    cooldown:
      default-days: 0
    groups:
      github-actions:
        patterns: ['*']
